name: "SMZDM Check-in Bot"

on:
  workflow_dispatch:

  # Uncomment below to schedule your job
  # schedule:
  #   - cron: "0 18 * * *"

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Working
        env:
          SMZDM_COOKIE: ${{ __ckguid=yPy2kF6kIvuNA4btL9nXl12; __jsluid_s=a9f2f2d27b0c8b96a4954ec4506c9619; device_id=19872249161664795846491373e0b6dfdee81c36e489802f414553251d; homepage_sug=d; r_sort_type=score; footer_floating_layer=0; sess=BA-gmzF4Xy%2BE%2BGASV2DNGiSSuM9IMkd4DT2BKno5uTfE15FgCZTLw7vM66Dvkx9yu8RsNncAJw0MAPa6bepFYPXNf2CGCf3T%2BijAIJpatnUCVQHbTqD%2F6S2vvY5; user=user%3A4757193081%7C4757193081; smzdm_id=4757193081; _zdmA.vid=*; ad_date=25; ad_json_feed=%7B%7D; Hm_lvt_9b7ac3d38f30fe89ff0b8a0546904e58=1671794699,1671882926,1671883472,1671966558; FROM_BD=1; DISABLE_APP_TIP=1; _zdmA.uid=ZDMA.lz7w6sj15.1671967843.2419200; sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%221839d90a19617-0e8bd5cc8d42cf-26021f51-2359296-1839d90a1971165%22%2C%22first_id%22%3A%22%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22%E8%87%AA%E7%84%B6%E6%90%9C%E7%B4%A2%E6%B5%81%E9%87%8F%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC%22%2C%22%24latest_referrer%22%3A%22https%3A%2F%2Fwww.google.com%2F%22%2C%22%24latest_landing_page%22%3A%22https%3A%2F%2Fwww.smzdm.com%2F%22%7D%2C%22%24device_id%22%3A%221839d90a19617-0e8bd5cc8d42cf-26021f51-2359296-1839d90a1971165%22%7D; bannerCounter=%5B%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A1%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%5D; Hm_lpvt_9b7ac3d38f30fe89ff0b8a0546904e58=1671967843; _zdmA.time=1671967843709.0.https%3A%2F%2Fwww.smzdm.com%2F }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
          SC_KEY: ${{ secrets.SC_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
        run: python main.py
